### ISSUE TITLE
Button text too big, wraps

### ISSUE THREAD

**Issue by nbuwe** [zeroflag/fcl#1]
Deteriorating eyesight makes me crank up the system font size a bit.  Unfortunately that makes already large button text even larger and makes it wrap.  Please, would it be possible to make the font-size adjust automatically for longer labels may be, or to have an option to override the system font size (that also affects stack display).

Samsung Galaxy A52, Android 12 / Samsung One UI 4.0.

![fcl-button-text-wraps (copy)](https://user-images.githubusercontent.com/17624538/155039782-b29f26e7-40aa-45cb-a5cd-cc2f946856b6.png)

**Comment by zeroflag** [comment]
Thanks for reporting this. We do have an automatic font size adjustment, but it might not work well if the system font size was changed. I'm looking into it.

**Comment by zeroflag** [comment]
I might have fixed it. It's difficult to reproduce the exact same situation, but I managed to get something very similar by setting the system font size to largest and the the display size to large.

Can you try it? It's available on the Beta track, version number is 152 (1.5-02).

In the play store, open the app page and click on Join the beta.

**Comment by nbuwe** [comment]
The button text is truncated now, so the layout is preserved.  Thanks!

**Comment by zeroflag** [comment]
Awesome. I might tweak it further to make it more robust. If you see any problems in the future let me know please.
